from __future__ import annotations

KPI_CONTRACT = {
    "profit_resilience": [
        {
            "id": "service_absorption_proxy_pct",
            "label": "Service Absorption % (Proxy)",
            "owner": "Owner/GM",
            "cadence": ["daily", "weekly", "monthly"],
            "target": 80.0,
            "description": "Percent of monthly overhead target covered by service + parts gross profit.",
            "formula": "(service_gp + parts_gp) / monthly_overhead_target * 100",
        },
        {
            "id": "department_gross_profit",
            "label": "Department Gross Profit",
            "owner": "Owner/GM",
            "cadence": ["daily", "weekly", "monthly"],
            "target": None,
            "description": "Gross profit generated by parts, service, and equipment streams.",
            "formula": "revenue - estimated_cost by stream",
        },
    ],
    "service_throughput_quality": [
        {
            "id": "technician_efficiency_pct",
            "label": "Technician Efficiency %",
            "owner": "Service Manager",
            "cadence": ["daily", "weekly"],
            "target": 85.0,
            "description": "Billed hours divided by available labor hours.",
            "formula": "sum(work_elapsed_hours) / (active_techs * standard_week_hours) * 100",
        },
        {
            "id": "open_work_orders_14_plus",
            "label": "Open Work Orders 14+ Days",
            "owner": "Service Manager",
            "cadence": ["daily", "weekly"],
            "target": 20.0,
            "description": "Count of open work orders aged more than 14 days.",
            "formula": "count(work_orders where status open and age_days > 14)",
        },
    ],
    "inventory_cash_efficiency": [
        {
            "id": "parts_turn_r12",
            "label": "Parts Turn Rate (R12)",
            "owner": "Parts Manager",
            "cadence": ["weekly", "monthly"],
            "target": 2.5,
            "description": "Trailing 12-month parts cost of sales over average inventory cost.",
            "formula": "r12_parts_sales_at_cost / r12_avg_inventory_cost",
        },
        {
            "id": "dead_stock_ratio_pct",
            "label": "Dead Stock Ratio %",
            "owner": "Parts Manager",
            "cadence": ["weekly", "monthly"],
            "target": 10.0,
            "description": "Share of parts with no sales in trailing 18 months.",
            "formula": "dead_parts_count / active_parts_count * 100",
        },
    ],
}


DEFAULT_THRESHOLDS = {
    "service_absorption_proxy_pct": {"warn_below": 65.0, "critical_below": 55.0},
    "technician_efficiency_pct": {"warn_below": 80.0, "critical_below": 70.0},
    "open_work_orders_14_plus": {"warn_above": 25.0, "critical_above": 40.0},
    "parts_turn_r12": {"warn_below": 2.0, "critical_below": 1.5},
    "dead_stock_ratio_pct": {"warn_above": 12.0, "critical_above": 18.0},
}


SUPPORTED_QUESTION_INTENTS = {
    "current_value": {
        "description": "Ask for current KPI value in selected period.",
        "examples": [
            "What is our dead stock ratio?",
            "Show tech efficiency for this period.",
        ],
    },
    "period_comparison": {
        "description": "Compare KPI value versus previous same-length period.",
        "examples": [
            "How did parts turns change versus last period?",
            "Are open work orders improving?",
        ],
    },
    "risk_summary": {
        "description": "Summarize which KPI thresholds are at risk.",
        "examples": [
            "What should I worry about right now?",
            "Which KPIs are in warning or critical?",
        ],
    },
}


QA_RESPONSE_SCHEMA = {
    "answer": "string",
    "evidence": "list[object]",
    "period": {"start_date": "YYYY-MM-DD", "end_date": "YYYY-MM-DD"},
    "assumptions": "list[string]",
    "confidence": "low|medium|high",
}
